### ISSUE TITLE
Doesn't work on first commit of a branch

### ISSUE THREAD

**Issue by pratik-parikh01** [Tj-Stockopedia/action-get-changed-folders#133]
This actions fails with the following error:
```
Error: Unable to retrieve commit data from github - Not Found
```
when your are running it for the first commit of a new branch. This is for v2.0.0 tag

**Comment by euangoddard** [comment]
Presumably this is happening here: https://github.com/Stockopedia/action-get-changed-files/blob/main/src/client.ts#L10. IN your case is the branch orphaned from another source branch (i.e. is there really no previous commit) or does this appear to be a facet of how the GitHub REST client works on new branches?

**Comment by EvaBender** [comment]
I get the same scenario when I create a new branch and push the first commit to the new branch. Is there no way to avoid getting an error when this happens?

**Comment by pratik-parikh01** [comment]
First commit here can be one of the following:
1. brand new branch with actually no previous commit
2. New branch created from another branch (master/main)
The error I posted was from the case 2 of the above. Sorry for replying so late. I used https://github.com/tj-actions/changed-files action with `fetch-depth: 0` (a param which fetches all commit history. Seemed excessive but that was the only way

**Comment by rb090** [comment]
I have the same issue. When pushing a new branch with commits I get the error

```
Error: Unable to retrieve commit data from github - Not Found
```

Using `fetch-depth: 0` does not help.

**Comment by taghoutikeyrus** [comment]
try this one 

```yaml
      - name: Get changed files
        id: microservices-directories
        uses: tj-actions/changed-files@v44
        with:
          dir_names: "true"
          fetch_depth: "0"
          dir_names_max_depth: 1
```
