### ISSUE TITLE
How to ignore two or more folders?

### ISSUE THREAD

**Issue by Sarga** [Tj-Stockopedia/action-get-changed-folders#41]
Hi there.
I need to add two folders to ignore. I tried next code, but no luck
```yaml
   - name: get all changed folders
      id: changed-folders
      uses: Stockopedia/action-get-changed-files@v1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        ignore: ".github depends"
        format: 'csv'
        foldersOnly: true
```

How to do that?  Thank you @Tj-Stockopedia
